# hello_qwen3_lora.yml — minimal LoRA fine-tune of Qwen3-1.7B on macOS (M-series)
base_model: Qwen/Qwen3-1.7B
model_type: qwen3
tokenizer_type: qwen3
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
strict: false

chat_template: qwen3 # Removed as it's model specific and not in the new config
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    split: train[:5%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
val_set_size: 0.0
output_dir: ./outputs/out
dataset_prepared_path: last_run_prepared

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:


# load_in_4bit: false # Removed as not in new config
# --- hardware / dtype ---
torch_dtype: float16  # MPS backend uses FP16
device_map: mps # Kept for macOS
fp16: true
trust_remote_code: true

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - down_proj
  - up_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model: checkpoint

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

gradient_checkpointing: true

sdp_attention: true  # Scaled‑dot‑product attention is the supported fallback on MPS

resume_from_checkpoint:
logging_steps: 1

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:
